# Generated by Django 4.1.3 on 2023-07-05 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_doctor_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Heading', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=10000)),
                ('subcontents', models.CharField(max_length=1000)),
                ('images', models.ImageField(blank=True, null=True, upload_to='contentphoto')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
