# Generated by Django 4.1.3 on 2023-07-05 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_service_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
